namespace CcsData.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public enum UsStateEnumBack
    {
        [Display(Name="AK - Alaska")]
        AK = 2,
        [Display(Name="AL - Alabama")]
        AL = 1,
        [Display(Name="AR - Arkansas")]
        AR = 5,
        [Display(Name="AS")]
        AS = 3,
        [Display(Name="AZ - Arizona")]
        AZ = 4,
        [Display(Name="CA - California")]
        CA = 6,
        [Display(Name="CO - Colorado")]
        CO = 7,
        [Display(Name="CT - Connecticut")]
        CT = 8,
        [Display(Name="DC - Washington DC")]
        DC = 10,
        [Display(Name="DE - Delaware")]
        DE = 9,
        [Display(Name="FL - Florida")]
        FL = 12,
        [Display(Name="FM -")]
        FM = 11,
        [Display(Name="GA - Georgia")]
        GA = 13,
        GU = 14,
        [Display(Name="HI - Hawaii")]
        HI = 15,
        [Display(Name="IA - Iowa")]
        IA = 0x13,
        [Display(Name="ID - Idaho")]
        ID = 0x10,
        [Display(Name="IL - Illinois")]
        IL = 0x11,
        [Display(Name="IN - Indiana")]
        IN = 0x12,
        [Display(Name="KS - Kansas")]
        KS = 20,
        [Display(Name="KY - Kentucky")]
        KY = 0x15,
        [Display(Name="LA - Louisiana")]
        LA = 0x16,
        [Display(Name="MA - Massachusetts")]
        MA = 0x1a,
        [Display(Name="MD - Maryland")]
        MD = 0x19,
        [Display(Name="ME - Maine")]
        ME = 0x17,
        [Display(Name="MH -")]
        MH = 0x18,
        [Display(Name="MI - Michigan")]
        MI = 0x1b,
        [Display(Name="MN - Minnesota")]
        MN = 0x1c,
        [Display(Name="MO - Missouri")]
        MO = 30,
        [Display(Name="MP -")]
        MP = 40,
        [Display(Name="MS - Mississippi")]
        MS = 0x1d,
        [Display(Name="MT - Montana")]
        MT = 0x1f,
        [Display(Name="NC - North Carolina")]
        NC = 0x26,
        [Display(Name="ND - North Dakota")]
        ND = 0x27,
        [Display(Name="NE - Nebraska")]
        NE = 0x20,
        [Display(Name="NH - New Hampshire")]
        NH = 0x22,
        [Display(Name="NJ - New Jersey")]
        NJ = 0x23,
        [Display(Name="NM - New Mexico")]
        NM = 0x24,
        [Display(Name="NV - Nevada")]
        NV = 0x21,
        [Display(Name="NY - New York")]
        NY = 0x25,
        [Display(Name="OH - Ohio")]
        OH = 0x29,
        [Display(Name="OK - Oklahoma")]
        OK = 0x2a,
        [Display(Name="OR - Oregon")]
        OR = 0x2b,
        [Display(Name="PA - Pennsylvania")]
        PA = 0x2d,
        [Display(Name="PR -")]
        PR = 0x2e,
        [Display(Name="PW -")]
        PW = 0x2c,
        [Display(Name="RI - Rhode Island")]
        RI = 0x30,
        [Display(Name="SC - South Carolina")]
        SC = 0x31,
        [Display(Name="SD - South Dakota")]
        SD = 50,
        [Display(Name="TN - Tennessee")]
        TN = 0x33,
        [Display(Name="TX - Texas")]
        TX = 0x34,
        [Display(Name="UT - Utah")]
        UT = 0x35,
        [Display(Name="VA - Virginia")]
        VA = 0x38,
        [Display(Name="VI -")]
        VI = 0x37,
        [Display(Name="VT - Vermont")]
        VT = 0x36,
        [Display(Name="WA - Washington")]
        WA = 0x39,
        [Display(Name="WI - Wisconsin")]
        WI = 0x3b,
        [Display(Name="WV - West Virginia")]
        WV = 0x3a,
        [Display(Name="WY - Wyoming")]
        WY = 60
    }
}

